/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_app;

import javax.swing.JOptionPane;
import static proyecto_app.Proyecto_APP.*;

/**
 *
 * @author LuisFernando
 */
public class Menu_Principal extends javax.swing.JFrame {
    public Clase_Persona Persona;
    public Clase_Identificador_de_Usuario Identificador_de_Usuario;
    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        Identificador_de_Usuario=new Clase_Identificador_de_Usuario(0,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        comboOpciones = new javax.swing.JComboBox<>();
        btn_Seleccionar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JFormattedTextField();
        lblArea = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblAntiguedad = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblNumerodeUsuario = new javax.swing.JLabel();
        lblTipodeEmpleado = new javax.swing.JLabel();
        lblDatos = new javax.swing.JLabel();
        txtArea = new javax.swing.JFormattedTextField();
        txtUsuario = new javax.swing.JFormattedTextField();
        txtSalario = new javax.swing.JFormattedTextField();
        txtAntiguedad = new javax.swing.JFormattedTextField();
        txtEdad = new javax.swing.JFormattedTextField();
        txtNumerodeUsuario = new javax.swing.JFormattedTextField();
        txtTipodeEmpleado = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        menuCalculadoraReactancia = new javax.swing.JMenu();
        menuLeyOhm = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        menuFiltros = new javax.swing.JMenuItem();
        menuCapacitor = new javax.swing.JMenuItem();
        menuResistenciaLED = new javax.swing.JMenuItem();
        menuNE555 = new javax.swing.JMenuItem();
        menuDeltaEstrella = new javax.swing.JMenuItem();
        menuConversorRangos = new javax.swing.JMenuItem();
        menuADC = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuAngulo = new javax.swing.JMenuItem();
        menuArea = new javax.swing.JMenuItem();
        menuAlmacenamiento = new javax.swing.JMenuItem();
        menuDensidad = new javax.swing.JMenuItem();
        menuEnergia = new javax.swing.JMenuItem();
        menuFlujo = new javax.swing.JMenuItem();
        menuFuerza = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setText("Opciones");

        comboOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_Seleccionar.setText("Seleccionar");
        btn_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(comboOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btn_Seleccionar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addComponent(comboOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Seleccionar)
                .addGap(25, 25, 25))
        );

        lblNombre.setText("Nombre:");

        txtNombre.setEditable(false);
        txtNombre.setText("txtNombre");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblArea.setText("Área:");

        lblUsuario.setText("Usuario:");

        lblSalario.setText("Salario:");

        lblAntiguedad.setText("Antiguedad:");

        lblEdad.setText("Edad:");

        lblNumerodeUsuario.setText("Numero de usuario:");

        lblTipodeEmpleado.setText("Tipo de empleado:");

        lblDatos.setText("Datos");

        txtArea.setEditable(false);
        txtArea.setText("txtArea");
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });

        txtUsuario.setEditable(false);
        txtUsuario.setText("txtUsuario");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtSalario.setEditable(false);
        txtSalario.setText("txtSalario");
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        txtAntiguedad.setEditable(false);
        txtAntiguedad.setText("txtAntiguedad");
        txtAntiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAntiguedadActionPerformed(evt);
            }
        });

        txtEdad.setEditable(false);
        txtEdad.setText("txtEdad");
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        txtNumerodeUsuario.setEditable(false);
        txtNumerodeUsuario.setText("txtNumerodeUsuario");
        txtNumerodeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerodeUsuarioActionPerformed(evt);
            }
        });

        txtTipodeEmpleado.setEditable(false);
        txtTipodeEmpleado.setText("txtTipodeEmpleado");
        txtTipodeEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipodeEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblArea)
                                    .addComponent(lblNombre)
                                    .addComponent(lblUsuario)
                                    .addComponent(lblSalario))
                                .addComponent(lblAntiguedad)
                                .addComponent(lblEdad)
                                .addComponent(lblNumerodeUsuario, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblTipodeEmpleado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumerodeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipodeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblDatos)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAntiguedad, lblArea, lblEdad, lblNombre, lblNumerodeUsuario, lblSalario, lblTipodeEmpleado, lblUsuario});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAntiguedad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumerodeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumerodeUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipodeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipodeEmpleado)))
        );

        jMenu1.setText("Matemáticas");

        jMenuItem1.setText("Geometria");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Ecuaciones");
        jMenu1.add(jMenuItem3);

        jMenu8.setText("Álgebra");

        jMenuItem7.setText("Calculadora de proporciones");
        jMenu8.add(jMenuItem7);

        jMenuItem8.setText("MCD y MCM");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuItem9.setText("Numero Primo");
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("Matrices");
        jMenu8.add(jMenuItem10);

        jMenu1.add(jMenu8);

        jMenu7.setText("Geometría Analitca");

        jMenuItem4.setText("Distancia entre 2 puntos");
        jMenu7.add(jMenuItem4);

        jMenuItem5.setText("Área del triangulo");
        jMenu7.add(jMenuItem5);

        jMenuItem6.setText("Ecuación del Circulo/Esfera");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenu1.add(jMenu7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Fisica e Ingenieria");

        jMenuItem2.setText("Caída libre");
        jMenu2.add(jMenuItem2);

        jMenuItem11.setText("Bloque con Fricción");
        jMenu2.add(jMenuItem11);

        jMenu9.setText("Termodinamica");

        jMenuItem12.setText("Expansión Lineal");
        jMenu9.add(jMenuItem12);

        jMenuItem13.setText("Expansión de Volumen");
        jMenu9.add(jMenuItem13);

        jMenuItem14.setText("Presión");
        jMenu9.add(jMenuItem14);

        jMenu2.add(jMenu9);

        jMenu10.setText("Óptica");

        jMenuItem15.setText("Refracción");
        jMenu10.add(jMenuItem15);

        jMenuItem16.setText("Prisma");
        jMenu10.add(jMenuItem16);

        jMenu2.add(jMenu10);

        jMenuBar1.add(jMenu2);

        menuCalculadoraReactancia.setText("Electrónica");

        menuLeyOhm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuLeyOhm.setText("Ley de Ohm");
        menuLeyOhm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLeyOhmActionPerformed(evt);
            }
        });
        menuCalculadoraReactancia.add(menuLeyOhm);

        jMenuItem18.setText("Calculadora de Reactancia/Resonancia");
        menuCalculadoraReactancia.add(jMenuItem18);

        menuFiltros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuFiltros.setText("Filtros");
        menuFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFiltrosActionPerformed(evt);
            }
        });
        menuCalculadoraReactancia.add(menuFiltros);

        menuCapacitor.setText("Carga del capacitor");
        menuCalculadoraReactancia.add(menuCapacitor);

        menuResistenciaLED.setText("Calculadora de Resistencia para el LED");
        menuCalculadoraReactancia.add(menuResistenciaLED);

        menuNE555.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNE555.setText("Calculadora NE555");
        menuNE555.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNE555ActionPerformed(evt);
            }
        });
        menuCalculadoraReactancia.add(menuNE555);

        menuDeltaEstrella.setText("Transformación Delta-Estrella");
        menuCalculadoraReactancia.add(menuDeltaEstrella);

        menuConversorRangos.setText("Conversor de Rangos");
        menuCalculadoraReactancia.add(menuConversorRangos);

        menuADC.setText("Convertidor Analógico-Digital");
        menuADC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuADCActionPerformed(evt);
            }
        });
        menuCalculadoraReactancia.add(menuADC);

        jMenuBar1.add(menuCalculadoraReactancia);

        jMenu5.setText("Conversión de Unidades");

        menuAngulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuAngulo.setText("Ángulo");
        menuAngulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnguloActionPerformed(evt);
            }
        });
        jMenu5.add(menuAngulo);

        menuArea.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuArea.setText("Área");
        menuArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaActionPerformed(evt);
            }
        });
        jMenu5.add(menuArea);

        menuAlmacenamiento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuAlmacenamiento.setText("Capacidad de Almacenamiento");
        menuAlmacenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlmacenamientoActionPerformed(evt);
            }
        });
        jMenu5.add(menuAlmacenamiento);

        menuDensidad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuDensidad.setText("Densidad");
        menuDensidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDensidadActionPerformed(evt);
            }
        });
        jMenu5.add(menuDensidad);

        menuEnergia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menuEnergia.setText("Energía, Trabajo");
        menuEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnergiaActionPerformed(evt);
            }
        });
        jMenu5.add(menuEnergia);

        menuFlujo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuFlujo.setText("Flujo Volumétrico");
        menuFlujo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFlujoActionPerformed(evt);
            }
        });
        jMenu5.add(menuFlujo);

        menuFuerza.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuFuerza.setText("Fuerza");
        menuFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuerzaActionPerformed(evt);
            }
        });
        jMenu5.add(menuFuerza);

        jMenuItem33.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem33.setText("Longitud");
        jMenu5.add(jMenuItem33);

        jMenuItem34.setText("Masa");
        jMenu5.add(jMenuItem34);

        jMenuItem35.setText("Potencia");
        jMenu5.add(jMenuItem35);

        jMenuItem36.setText("Presión");
        jMenu5.add(jMenuItem36);

        jMenuItem37.setText("Sistemas de Numeración");
        jMenu5.add(jMenuItem37);

        jMenuItem38.setText("Temperatura");
        jMenu5.add(jMenuItem38);

        jMenuItem39.setText("Tiempo");
        jMenu5.add(jMenuItem39);

        jMenuItem40.setText("Velocidad");
        jMenu5.add(jMenuItem40);

        jMenuItem41.setText("Volumen");
        jMenu5.add(jMenuItem41);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Acciones");

        menuCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuCerrarSesion.setText("Cerrar Sesión");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu6.add(menuCerrarSesion);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuADCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuADCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuADCActionPerformed

    private void menuEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnergiaActionPerformed
        // TODO add your handling code here:
        Conversor_Unidades=new Ventana_Conversor_Unidades();
        Conversor_Unidades.setVisible(true);
        Conversor_Unidades.Cargar_Menu(Magnitudes_Fisicas.getItem(4));
        this.setVisible(false);
    }//GEN-LAST:event_menuEnergiaActionPerformed

    private void menuLeyOhmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLeyOhmActionPerformed
        // TODO add your handling code here:
        Ley_de_Ohm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuLeyOhmActionPerformed

    private void menuNE555ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNE555ActionPerformed
        // TODO add your handling code here:
        NE555.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuNE555ActionPerformed

    private void menuFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFiltrosActionPerformed
        // TODO add your handling code here:
        Filtros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuFiltrosActionPerformed

    private void menuAnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnguloActionPerformed
        // TODO add your handling code here:
        Conversor_Unidades=new Ventana_Conversor_Unidades();
        Conversor_Unidades.setVisible(true);
        Conversor_Unidades.Cargar_Menu(Magnitudes_Fisicas.getItem(0));
        this.setVisible(false);
    }//GEN-LAST:event_menuAnguloActionPerformed

    private void menuAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaActionPerformed
        // TODO add your handling code here:
        Conversor_Unidades=new Ventana_Conversor_Unidades();
        Conversor_Unidades.setVisible(true);
        Conversor_Unidades.Cargar_Menu(Magnitudes_Fisicas.getItem(1));
        this.setVisible(false);
    }//GEN-LAST:event_menuAreaActionPerformed

    private void menuAlmacenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlmacenamientoActionPerformed
        // TODO add your handling code here:
        Conversor_Unidades=new Ventana_Conversor_Unidades();
        Conversor_Unidades.setVisible(true);
        Conversor_Unidades.Cargar_Menu(Magnitudes_Fisicas.getItem(2));
        this.setVisible(false);
    }//GEN-LAST:event_menuAlmacenamientoActionPerformed

    private void menuDensidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDensidadActionPerformed
        // TODO add your handling code here:
        Conversor_Unidades=new Ventana_Conversor_Unidades();
        Conversor_Unidades.setVisible(true);
        Conversor_Unidades.Cargar_Menu(Magnitudes_Fisicas.getItem(3));
        this.setVisible(false);
    }//GEN-LAST:event_menuDensidadActionPerformed

    private void menuFlujoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFlujoActionPerformed
        // TODO add your handling code here:
        Conversor_Unidades=new Ventana_Conversor_Unidades();
        Conversor_Unidades.setVisible(true);
        Conversor_Unidades.Cargar_Menu(Magnitudes_Fisicas.getItem(5));
        this.setVisible(false);
    }//GEN-LAST:event_menuFlujoActionPerformed

    private void menuFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuerzaActionPerformed
        // TODO add your handling code here:
        Conversor_Unidades=new Ventana_Conversor_Unidades();
        Conversor_Unidades.setVisible(true);
        Conversor_Unidades.Cargar_Menu(Magnitudes_Fisicas.getItem(6));
        this.setVisible(false);
    }//GEN-LAST:event_menuFuerzaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAntiguedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAntiguedadActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtNumerodeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerodeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerodeUsuarioActionPerformed

    private void txtTipodeEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipodeEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipodeEmpleadoActionPerformed

    private void btn_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarActionPerformed
        // TODO add your handling code here:
        switch (Persona.getTipo_de_Empleado()) {
            case 0:
                Opciones_de_Gerente();
                break;
            case 1:
                Opciones_de_Recursos_Humanos();
                break;
            case 2:
                Opciones_de_Jefe();
                break;
            case 3:
                Opciones_de_Ingeniero();
                break;
            default:
                Opciones_de_Obrero();
                break;
        }
    }//GEN-LAST:event_btn_SeleccionarActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       Bienvenida.Limpiar_Texto();
       Bienvenida.setVisible(true);
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Seleccionar;
    private javax.swing.JComboBox<String> comboOpciones;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAntiguedad;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumerodeUsuario;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTipodeEmpleado;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuADC;
    private javax.swing.JMenuItem menuAlmacenamiento;
    private javax.swing.JMenuItem menuAngulo;
    private javax.swing.JMenuItem menuArea;
    private javax.swing.JMenu menuCalculadoraReactancia;
    private javax.swing.JMenuItem menuCapacitor;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuConversorRangos;
    private javax.swing.JMenuItem menuDeltaEstrella;
    private javax.swing.JMenuItem menuDensidad;
    private javax.swing.JMenuItem menuEnergia;
    private javax.swing.JMenuItem menuFiltros;
    private javax.swing.JMenuItem menuFlujo;
    private javax.swing.JMenuItem menuFuerza;
    private javax.swing.JMenuItem menuLeyOhm;
    private javax.swing.JMenuItem menuNE555;
    private javax.swing.JMenuItem menuResistenciaLED;
    private javax.swing.JFormattedTextField txtAntiguedad;
    private javax.swing.JFormattedTextField txtArea;
    private javax.swing.JFormattedTextField txtEdad;
    private javax.swing.JFormattedTextField txtNombre;
    private javax.swing.JFormattedTextField txtNumerodeUsuario;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JFormattedTextField txtTipodeEmpleado;
    private javax.swing.JFormattedTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void Cargar_datos_de_Usuario(Clase_Identificador_de_Usuario Identificador_de_Usuario) {
     setLocationRelativeTo(this);
     Persona=new Clase_Persona();
     this.Identificador_de_Usuario.Numero_de_Area=Identificador_de_Usuario.Numero_de_Area;
     this.Identificador_de_Usuario.Numero_de_Empleado=Identificador_de_Usuario.Numero_de_Empleado;
     Persona=Personal.getItem(Identificador_de_Usuario.Numero_de_Area).getItem(Identificador_de_Usuario.Numero_de_Empleado);
     txtNombre.setText(Persona.getNombre()+" "+Persona.getApellido_Paterno()+" "+Persona.getApellido_Materno());
     txtArea.setText(Persona.getArea());
     txtUsuario.setText(Persona.getUsuario());
     txtSalario.setText(""+Persona.getSalario());
     txtAntiguedad.setText(""+Persona.Antiguedad+" años");
     txtEdad.setText(""+Persona.Edad+" años");
     txtNumerodeUsuario.setText(""+Persona.getNumero_Usuario());
     txtTipodeEmpleado.setText(Persona.get_Tipo_de_Empleado());
     comboOpciones.removeAllItems();
     int i;
     String[] Cadena=Persona.Obtener_Opciones();
     for (i=0;i<Cadena.length;i++){
     comboOpciones.addItem(Cadena[i]);}
    }

    private void Opciones_de_Gerente() {
         //Opcion0="Modificar Información Personal";
         //Opcion1="Modificar Información de otro Usuario";
         //Opcion2="Agregar Área";
         //Opcion3="Agregar Empleado";
         //Opcion4="Ver Personal";
         //Modificar Información Personal(Clase_Identificador_de_Usuario Identificador_de_Usuario,int Tipo_de_usuario);
        int opcion_seleccionada=comboOpciones.getSelectedIndex();
        switch (opcion_seleccionada) {
            case 0:
                Edicion_Personal();
                break;
            case 1:
                Edicion_de_Empleados();
                break;
            case 2:
                Agregar_Area();
                break;
            case 3:
                Agregar_Empleado();
                break;
            default:
                 Ver_Personal_Empresa();
                break;
        }
    }
    
    private void Opciones_de_Recursos_Humanos() {
         //Opcion0="Modificar Información Personal";
         //Opcion1="Modificar Información de otro Usuario";
         //Opcion2="Agregar Área";
         //Opcion3="Agregar Empleado";
         //Opcion4="Ver Personal";
        int opcion_seleccionada=comboOpciones.getSelectedIndex();
        switch (opcion_seleccionada) {
            case 0:
                Edicion_Personal();
                break;
            case 1:
                Edicion_de_Empleados();
                break;
            case 2:
                Agregar_Area();
                break;
            case 3:
                Agregar_Empleado();
                break;
            default:
                 Ver_Personal_Empresa();
                break;
        }
    }

    private void Opciones_de_Jefe() {
        //Opcion[0]="Modificar Información Personal";
        //Opcion[1]="Modificar Información de otro Usuario";
        //Opcion[2]="Ver Personal a cargo";
        int opcion_seleccionada=comboOpciones.getSelectedIndex();
        switch (opcion_seleccionada) {
            case 0:
                Edicion_Personal();
                break;
            case 1:
                Edicion_de_Empleados();
                break;
            default:
                 Ver_Personal_Empresa();
                break;
        }
    }

    private void Opciones_de_Ingeniero() {
        //Opcion[0]="Modificar Información Personal";
        //Opcion[1]="Ver Personal a cargo";
        int opcion_seleccionada=comboOpciones.getSelectedIndex();
        switch (opcion_seleccionada) {
            case 0:
                Edicion_Personal();
                break;
            case 1:
                Ver_Personal_Empresa();
                break;
            default:
                Manipular_carro();
                break;
        }
    }

    private void Opciones_de_Obrero() {
        //Opcion[0]="Modificar Información Personal";
        int opcion_seleccionada=comboOpciones.getSelectedIndex();
        switch (opcion_seleccionada) {
            case 0:
                Edicion_Personal();
                break;
            default:
                Ver_Personal_Empresa();
                break;
        }
    }
    private void Edicion_Personal(){
     Edicion_de_Datos=new Ventana_Edicion_de_Datos();
     Edicion_de_Datos.Modificar_Información_Personal(Identificador_de_Usuario);
     Edicion_de_Datos.setVisible(true);
     this.setVisible(false);
    }
    private void Edicion_de_Empleados(){
     Clase_Persona Persona_Seleccionada;
     int area=Persona.getNumero_Area();
     int i,Numero_de_Empleados=Personal.getItem(area).getSize();
     int Trabajadores=0;
     for (i=0;i<Numero_de_Empleados;i++){
         Persona_Seleccionada=new Clase_Persona();
         Persona_Seleccionada=Personal.getItem(area).getItem(i);
         if(Persona_Seleccionada.getTipo_de_Empleado()!=2){
          Trabajadores=Trabajadores+1;
         }
       }
     if (Trabajadores>0){
     Edicion_de_Datos=new Ventana_Edicion_de_Datos();
     Edicion_de_Datos.Modificar_Informacion_Empleados(Identificador_de_Usuario);
     Edicion_de_Datos.setVisible(true);
     this.setVisible(false);}
     else{
       JOptionPane.showMessageDialog(null, "No se puede editar ya que no posee trabajadores a administrar",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);  
       //System.out.println("No posee trabajadores a administrar");
     }
    }

    private void Agregar_Empleado() {
      Agregar_Empleados.Agregar_Datos_de_Empleado(Identificador_de_Usuario);
      Agregar_Empleados.setVisible(true);
      this.setVisible(false);
    }

    private void Agregar_Area() {
        Nueva_Area.setVisible(true);
        this.setVisible(false);
    }
    
    private void Ver_Personal_Empresa() {
        Ver_Personal=new Ventana_Ver_Personal();
        Ver_Personal.Mostrar_Tabla();
        Ver_Personal.setVisible(true);
        this.setVisible(false);
    }

    private void Manipular_carro() {
       if (Comunicacion_Serial.Inicializar_Comunicacion_Serial()){
       Comunicacion_Serial.setVisible(true);
       this.setVisible(false);}
    }
}