/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_app;

import javax.swing.JButton;

/**
 *
 * @author LuisFernando
 */
public class Panel_opcion extends javax.swing.JPanel {
   //public JButton Prueba;
    /**
     * Creates new form Panel_opcion
     */
    public Panel_opcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidad = new javax.swing.JTextField();
        comboPrefijo = new javax.swing.JComboBox<>();

        txtCantidad.setText("Cantidad");
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        comboPrefijo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed
    public void Habiltar_Prefijos(boolean s){
      comboPrefijo.setEnabled(s);
    }
    public double getNumber_txtCantidad(){
        //return (float)Float.valueOf(txtCantidad.getText());
       try{
        return Double.valueOf(txtCantidad.getText());
       }
       catch(NumberFormatException e){
        System.out.println("No es número");
        return 0;
       }
    }
    
    public String getText_txtCantidad(){
       return txtCantidad.getText();
    }   
    public void setSelectedItem_comboPrefijo(int a){
       comboPrefijo.setSelectedIndex(a);
    }
    public void setText_txtCantidad(String Texto){
       txtCantidad.setText(Texto);
    }        
    public void addItem_comboPrefijo(String Texto){
     comboPrefijo.addItem(Texto);
    }
    public void removeAllItems_comboPrefijo(){
     comboPrefijo.removeAllItems();
    }
    public int getSelectedIndex_comboPrefijo(){
     return comboPrefijo.getSelectedIndex();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboPrefijo;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
