/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_app;
import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import static proyecto_app.Proyecto_APP.Principal;
/**
 *
 * @author LuisFernando
 */
public class Ventana_Comunicacion_Serial extends javax.swing.JFrame {
    private OutputStream salidadatos=null;
    SerialPort puertoserial;
    String puertoquemarcaelarduino="COM4";
    int TIMEOUT=5000; //Milisegundos
    int DATA_RATE=9600;
    boolean estado=false;
    int Velocidad;
    /**
     * Creates new form Ventana_Comunicacion_Serial
     */
    public Ventana_Comunicacion_Serial() {
        initComponents();
        Velocidad=sliderVelocidad.getValue();
        lblVelocidad.setText(""+Velocidad);
        //Inicializar_Comunicacion_Serial();
    }
    public boolean MetodoConexion(){
        CommPortIdentifier puertoencontrado=null;
        Enumeration enumeracionpuerto=CommPortIdentifier.getPortIdentifiers();//ahora vamos a obtener la enumeracion de los puertos que tengamos
        while(enumeracionpuerto.hasMoreElements()){
            CommPortIdentifier auxpuerto=(CommPortIdentifier) enumeracionpuerto.nextElement();
            if(puertoquemarcaelarduino.equals(auxpuerto.getName())){
                puertoencontrado=auxpuerto;
                break;
                }
            }
        
        if(puertoencontrado==null){
            muestraerrorconexion("No se encontro el puerto");
            return false;
            //System.exit(ERROR);
            }
        else{
        try{
            puertoserial = (SerialPort) puertoencontrado.open(this.getClass().getName(), TIMEOUT);//abrir el puerto serie
            puertoserial.setSerialPortParams(DATA_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            salidadatos = puertoserial.getOutputStream();
            return true;
            } catch(Exception variableexcepcion){
                muestraerrorconexion(variableexcepcion.getMessage());
                return false;
                //System.exit(ERROR);
            }
        }
    }    
    private void enviarDatos(String datos){
        try {
            salidadatos.write(datos.getBytes());
        } catch (IOException ex) {
             muestraerrorconexion(ex.getMessage());
                //System.exit(ERROR);
        }
        }        
    public void muestraerrorconexion(String mensaje){
        JOptionPane.showMessageDialog(rootPane, mensaje);
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrender = new javax.swing.JButton();
        btnNorte = new javax.swing.JButton();
        btnParo = new javax.swing.JButton();
        btnSur = new javax.swing.JButton();
        btnEste = new javax.swing.JButton();
        btneOeste = new javax.swing.JButton();
        btnNoreste = new javax.swing.JButton();
        btnNoroeste = new javax.swing.JButton();
        btnSureste = new javax.swing.JButton();
        btnSuroeste = new javax.swing.JButton();
        sliderVelocidad = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        lblVelocidad = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRegresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPrender.setText("Prender");
        btnPrender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrenderActionPerformed(evt);
            }
        });

        btnNorte.setText("Norte");
        btnNorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNorteActionPerformed(evt);
            }
        });

        btnParo.setText("Paro");
        btnParo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParoActionPerformed(evt);
            }
        });

        btnSur.setText("Sur");
        btnSur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurActionPerformed(evt);
            }
        });

        btnEste.setText("Este");
        btnEste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsteActionPerformed(evt);
            }
        });

        btneOeste.setText("Oeste");
        btneOeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneOesteActionPerformed(evt);
            }
        });

        btnNoreste.setText("Noreste");
        btnNoreste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoresteActionPerformed(evt);
            }
        });

        btnNoroeste.setText("Noroeste");
        btnNoroeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoroesteActionPerformed(evt);
            }
        });

        btnSureste.setText("Sureste");
        btnSureste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuresteActionPerformed(evt);
            }
        });

        btnSuroeste.setText("Suroeste");
        btnSuroeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuroesteActionPerformed(evt);
            }
        });

        sliderVelocidad.setMaximum(255);
        sliderVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVelocidadStateChanged(evt);
            }
        });
        sliderVelocidad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                sliderVelocidadCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel1.setText("Velocidad");

        lblVelocidad.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btneOeste, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSuroeste, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btnNoroeste))
                            .addGap(183, 183, 183))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnParo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNorte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSureste)
                                .addComponent(btnEste, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNoreste))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVelocidad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrender)
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNorte)
                    .addComponent(btnNoreste)
                    .addComponent(btnNoroeste))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParo)
                    .addComponent(btnEste)
                    .addComponent(btneOeste))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnSuroeste))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSur)
                            .addComponent(btnSureste))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVelocidad))
                .addGap(18, 18, 18)
                .addComponent(btnPrender)
                .addContainerGap())
        );

        jMenu1.setText("Acciones");

        menuRegresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuRegresar.setText("Regresar");
        menuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegresarActionPerformed(evt);
            }
        });
        jMenu1.add(menuRegresar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnPrenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrenderActionPerformed
        // TODO add your handling code here:
        if(estado==true){//Prende Lámpara
          estado=false;
          btnPrender.setText("Apagar");
          enviarDatos("9r");//Prender Lampara
        }
        else{//Apagar Lámpara
          estado=true;
          btnPrender.setText("Prender");
          enviarDatos("10r");//Apagar Lampara
        }
    }//GEN-LAST:event_btnPrenderActionPerformed

    private void menuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Principal.setVisible(true);
        enviarDatos("8r");//Paro
        enviarDatos("10r");//Apagar Lampara
        puertoserial.close();
    }//GEN-LAST:event_menuRegresarActionPerformed

    private void btneOesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneOesteActionPerformed
        // TODO add your handling code here:
        enviarDatos("4r");
    }//GEN-LAST:event_btneOesteActionPerformed

    private void btnSuresteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuresteActionPerformed
        // TODO add your handling code here:
        enviarDatos("7r");
    }//GEN-LAST:event_btnSuresteActionPerformed

    private void sliderVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVelocidadStateChanged
        // TODO add your handling code here:
        Velocidad=sliderVelocidad.getValue(); 
        lblVelocidad.setText(""+Velocidad);
        enviarDatos("11r"+Velocidad+"r");
    }//GEN-LAST:event_sliderVelocidadStateChanged

    private void sliderVelocidadCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sliderVelocidadCaretPositionChanged
        // TODO add your handling code here:
        //Velocidad=sliderVelocidad.getValue(); 
        //lblVelocidad.setText(""+Velocidad);
    }//GEN-LAST:event_sliderVelocidadCaretPositionChanged

    private void btnEsteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsteActionPerformed
        // TODO add your handling code here:
        enviarDatos("0r");
    }//GEN-LAST:event_btnEsteActionPerformed

    private void btnNoresteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoresteActionPerformed
        // TODO add your handling code here:
        enviarDatos("1r");
    }//GEN-LAST:event_btnNoresteActionPerformed

    private void btnNorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNorteActionPerformed
        // TODO add your handling code here:
        enviarDatos("2r");
    }//GEN-LAST:event_btnNorteActionPerformed

    private void btnNoroesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoroesteActionPerformed
        // TODO add your handling code here:
        enviarDatos("3r");
    }//GEN-LAST:event_btnNoroesteActionPerformed

    private void btnSuroesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuroesteActionPerformed
        // TODO add your handling code here:
        enviarDatos("5r");
    }//GEN-LAST:event_btnSuroesteActionPerformed

    private void btnSurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurActionPerformed
        // TODO add your handling code here:
        enviarDatos("6r");
    }//GEN-LAST:event_btnSurActionPerformed

    private void btnParoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParoActionPerformed
        // TODO add your handling code here:
        enviarDatos("8r");
    }//GEN-LAST:event_btnParoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Comunicacion_Serial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Comunicacion_Serial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Comunicacion_Serial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Comunicacion_Serial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Comunicacion_Serial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEste;
    private javax.swing.JButton btnNoreste;
    private javax.swing.JButton btnNoroeste;
    private javax.swing.JButton btnNorte;
    private javax.swing.JButton btnParo;
    private javax.swing.JButton btnPrender;
    private javax.swing.JButton btnSur;
    private javax.swing.JButton btnSureste;
    private javax.swing.JButton btnSuroeste;
    private javax.swing.JButton btneOeste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblVelocidad;
    private javax.swing.JMenuItem menuRegresar;
    private javax.swing.JSlider sliderVelocidad;
    // End of variables declaration//GEN-END:variables

    public boolean Inicializar_Comunicacion_Serial(){
      return MetodoConexion();     
    }
}
