/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_app;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyecto_app.Proyecto_APP.Magnitudes_Fisicas;
import static proyecto_app.Proyecto_APP.Principal;

/**
 *
 * @author LuisFernando
 */
public class Ventana_Conversor_Unidades extends javax.swing.JFrame {
    Clase_Magnitud_Fisica Magnitud_Fisica;
    boolean Inicio_Ventana=false;
    DefaultTableModel Tabla=new DefaultTableModel();
    /**
     * Creates new form Ventana_Conversor_Unidades
     */
    public Ventana_Conversor_Unidades() {
        initComponents();
        Tabla.addColumn("Nombre");
        Tabla.addColumn("Valor");
        Tabla.addColumn("Abreviatura");
        tablaUnidades.setModel(Tabla);
        //Cargar_Menu(Magnitudes_Fisicas.getItem(0));
    }
    public void Modificar_Tabla(){
        int a;
        a=comboAbr1.getSelectedIndex();
        Magnitud_Fisica.getItem(a).Valor=Double.valueOf(txtValor1.getText());
        while(Tabla.getRowCount()>0){
         Tabla.removeRow(0);
        }
        for (int b=0;b<Magnitud_Fisica.getSize();b++){
         String Datos[]=new String[3];
         Magnitud_Fisica.Realizar_Conversion(Magnitud_Fisica.getItem(a),Magnitud_Fisica.getItem(b));
         Datos[0]=Magnitud_Fisica.getItem(b).Nombre;
         Datos[1]=""+Magnitud_Fisica.getItem(b).Valor;
         Datos[2]=""+Magnitud_Fisica.getItem(b).Abreviatura;
         Tabla.addRow(Datos);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNombre1 = new javax.swing.JLabel();
        comboAbr1 = new javax.swing.JComboBox<>();
        txtValor1 = new javax.swing.JFormattedTextField();
        lblNombre2 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JFormattedTextField();
        comboAbr2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUnidades = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre1.setText("lblNombre1");

        comboAbr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAbr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAbr1ActionPerformed(evt);
            }
        });

        txtValor1.setText("txtValor1");
        txtValor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValor1FocusLost(evt);
            }
        });
        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });

        lblNombre2.setText("lblNombre2");

        txtValor2.setEditable(false);
        txtValor2.setText("txtValor2");

        comboAbr2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAbr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAbr2ActionPerformed(evt);
            }
        });

        tablaUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unidad", "Valor", "Abreviatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUnidades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tablaUnidades);
        if (tablaUnidades.getColumnModel().getColumnCount() > 0) {
            tablaUnidades.getColumnModel().getColumn(0).setResizable(false);
            tablaUnidades.getColumnModel().getColumn(1).setResizable(false);
            tablaUnidades.getColumnModel().getColumn(2).setResizable(false);
        }

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jMenu1.setText("Acciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Regresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValor2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(txtValor1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboAbr1, 0, 87, Short.MAX_VALUE)
                    .addComponent(comboAbr2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnRegresar)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnRegresar)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(comboAbr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre2)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAbr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
        Modificar_Valor();
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void comboAbr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAbr1ActionPerformed
        // TODO add your handling code here:
        Modificar_Valor();
    }//GEN-LAST:event_comboAbr1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void comboAbr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAbr2ActionPerformed
        // TODO add your handling code here:
        Modificar_Valor();
    }//GEN-LAST:event_comboAbr2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtValor1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValor1FocusLost
        // TODO add your handling code here:
         Modificar_Valor();
    }//GEN-LAST:event_txtValor1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Conversor_Unidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Conversor_Unidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Conversor_Unidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Conversor_Unidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Conversor_Unidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboAbr1;
    private javax.swing.JComboBox<String> comboAbr2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JTable tablaUnidades;
    private javax.swing.JFormattedTextField txtValor1;
    private javax.swing.JFormattedTextField txtValor2;
    // End of variables declaration//GEN-END:variables
    
    public boolean isnan(String Texto){
        //return (float)Float.valueOf(txtCantidad.getText());
       try{
        Double.valueOf(Texto);
        return true;
       }
       catch(NumberFormatException e){
        return false;
       }
       
    }
    private void Modificar_Valor(){
     if (Inicio_Ventana){
        int a,b;
         a=comboAbr1.getSelectedIndex();
         b=comboAbr2.getSelectedIndex();
         lblNombre1.setText(Magnitud_Fisica.getItem(a).Nombre);
         lblNombre2.setText(Magnitud_Fisica.getItem(b).Nombre);
         if (isnan(txtValor1.getText())){
          Magnitud_Fisica.getItem(a).Valor=Double.valueOf(txtValor1.getText());
          Magnitud_Fisica.Realizar_Conversion(Magnitud_Fisica.getItem(a),Magnitud_Fisica.getItem(b));
          txtValor2.setText(""+Magnitud_Fisica.getItem(b).Valor);
          Modificar_Tabla();
         }
         else
         {
           txtValor1.setText("1");
           Magnitud_Fisica.getItem(a).Valor=Double.valueOf(txtValor1.getText());
           Magnitud_Fisica.Realizar_Conversion(Magnitud_Fisica.getItem(a),Magnitud_Fisica.getItem(b));
           txtValor2.setText(""+Magnitud_Fisica.getItem(b).Valor);
           JOptionPane.showMessageDialog(null, "Ingrese un valor válido",
           "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);   
         }
        }
    }
    public void Cargar_Menu(Clase_Magnitud_Fisica Magnitud_Fisica) {
        this.Magnitud_Fisica=Magnitud_Fisica;
        int tamano=Magnitud_Fisica.getSize();
        comboAbr1.removeAllItems();
        comboAbr2.removeAllItems();
        lblNombre1.setText(Magnitud_Fisica.getItem(0).Nombre);
        lblNombre2.setText(Magnitud_Fisica.getItem(1).Nombre);
        txtValor1.setText(""+Magnitud_Fisica.getItem(0).Valor);
        Magnitud_Fisica.Realizar_Conversion(Magnitud_Fisica.getItem(0),Magnitud_Fisica.getItem(1));
        txtValor2.setText(""+Magnitud_Fisica.getItem(1).Valor);
        for (int i=0;i<tamano;i++){
         comboAbr1.addItem(Magnitud_Fisica.getItem(i).Abreviatura);
         comboAbr2.addItem(Magnitud_Fisica.getItem(i).Abreviatura);
        }
        comboAbr2.setSelectedIndex(1);
        Inicio_Ventana=true;
        Modificar_Tabla();
    }
}