/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_app;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyecto_app.Proyecto_APP.*;

/**
 *
 * @author LuisFernando
 */
public class Ventana_Edicion_de_Datos extends javax.swing.JFrame {
    Clase_Persona Persona_Editor,Persona_Seleccionada;
    Clase_Identificador_de_Usuario Identificador_de_Usuario_Editor,Identificador_de_Usuario_Seleccionado;
    Clase_Identificadores_de_Usuarios Identificadores_de_Usuarios;
    int modo;//0-Modo de Edición Personal,1-Modo Edición General.
    boolean inicializado=false;
    DefaultTableModel Tabla=new DefaultTableModel();
    /**
     * Creates new form Ventana_Edicion_de_Datos
     */
    public Ventana_Edicion_de_Datos() {
        initComponents();
        Identificadores_de_Usuarios=new Clase_Identificadores_de_Usuarios();
        Tabla.addColumn("Nombre");
        Tabla.addColumn("Área");
        Tabla.addColumn("Tipo de Empleado");
        Tabla.addColumn("Usuario");
        Tabla.addColumn("# Usuario");
        Tabla.addColumn("Edad");
        Tabla.addColumn("Salario");
        tablaEmpleados.setModel(Tabla);
        tablaEmpleados.setEnabled(false);
        //Agregar_Columna();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        comboEmpleados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        lblNombre2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblAntiguedad = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblNumerodeUsuario = new javax.swing.JLabel();
        lblTipodeEmpleado = new javax.swing.JLabel();
        txtTipodeEmpleado = new javax.swing.JFormattedTextField();
        txtNumerodeUsuario = new javax.swing.JFormattedTextField();
        txtEdad = new javax.swing.JFormattedTextField();
        txtAntiguedad = new javax.swing.JFormattedTextField();
        txtSalario = new javax.swing.JFormattedTextField();
        txtUsuario = new javax.swing.JFormattedTextField();
        txtArea = new javax.swing.JFormattedTextField();
        txtNombre = new javax.swing.JFormattedTextField();
        btnGuardar = new javax.swing.JButton();
        btnResetear = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JFormattedTextField();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JFormattedTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuResetear = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRegresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmpleadosActionPerformed(evt);
            }
        });

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Area", "Usuario", "# Usuario", "Edad", "Salario"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        lblNombre2.setText("Empleados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblNombre2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        lblNombre.setText("Nombre:");

        lblArea.setText("Área:");

        lblUsuario.setText("Usuario:");

        lblSalario.setText("Salario:");

        lblAntiguedad.setText("Antiguedad:");

        lblEdad.setText("Edad:");

        lblNumerodeUsuario.setText("Numero de usuario:");

        lblTipodeEmpleado.setText("Tipo de empleado:");

        txtTipodeEmpleado.setText("txtTipodeEmpleado");
        txtTipodeEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipodeEmpleadoActionPerformed(evt);
            }
        });

        txtNumerodeUsuario.setText("txtNumerodeUsuario");
        txtNumerodeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumerodeUsuarioFocusLost(evt);
            }
        });
        txtNumerodeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerodeUsuarioActionPerformed(evt);
            }
        });

        txtEdad.setText("txtEdad");
        txtEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadFocusLost(evt);
            }
        });
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        txtAntiguedad.setText("txtAntiguedad");
        txtAntiguedad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAntiguedadFocusLost(evt);
            }
        });
        txtAntiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAntiguedadActionPerformed(evt);
            }
        });

        txtSalario.setText("txtSalario");
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        txtUsuario.setText("txtUsuario");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtArea.setText("txtArea");
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });

        txtNombre.setText("txtNombre");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnResetear.setText("Resetear");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });

        lblNombre1.setText("Datos");

        txtApellidoPaterno.setText("txtApellidoPaterno");
        txtApellidoPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoPaternoFocusLost(evt);
            }
        });
        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });

        lblApellidoPaterno.setText("Apellido Paterno:");

        lblApellidoMaterno.setText("Apellido Materno:");

        txtApellidoMaterno.setText("txtApellidoMaterno");
        txtApellidoMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoMaternoFocusLost(evt);
            }
        });
        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });

        lblContrasena.setText("Contraseña:");

        txtContrasena.setText("txtContrasena");
        txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasenaFocusLost(evt);
            }
        });
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNombre1)
                .addGap(185, 185, 185))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnGuardar)
                .addGap(72, 72, 72)
                .addComponent(btnResetear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblContrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumerodeUsuario)
                            .addComponent(lblEdad)
                            .addComponent(lblAntiguedad)
                            .addComponent(lblSalario)
                            .addComponent(lblUsuario)
                            .addComponent(lblArea)
                            .addComponent(lblNombre)
                            .addComponent(lblApellidoPaterno)
                            .addComponent(lblApellidoMaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumerodeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipodeEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTipodeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoPaterno)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoMaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAntiguedad)
                    .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumerodeUsuario)
                    .addComponent(txtNumerodeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipodeEmpleado)
                    .addComponent(txtTipodeEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnResetear))
                .addContainerGap())
        );

        jMenu1.setText("Editar");

        menuResetear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuResetear.setText("Cargar de nuevo");
        menuResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuResetearActionPerformed(evt);
            }
        });
        jMenu1.add(menuResetear);

        menuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(menuGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acciones");

        menuRegresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuRegresar.setText("Regresar");
        menuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegresarActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegresar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegresarActionPerformed
        // TODO add your handling code here:
        inicializado=false;
        Principal.Cargar_datos_de_Usuario(Identificador_de_Usuario_Editor);
        Principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuRegresarActionPerformed

    private void txtTipodeEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipodeEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipodeEmpleadoActionPerformed

    private void txtNumerodeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerodeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerodeUsuarioActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
        Editar_Edad();
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAntiguedadActionPerformed
        // TODO add your handling code here:
        Editar_Antiguedad();
    }//GEN-LAST:event_txtAntiguedadActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
        Editar_Salario();
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        Editar_Usuario();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        Editar_Nombre();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (modo==0){
        Guardar_Personal();}
        else{
        Guardar_Empleado();}
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
        Editar_ApellidoPaterno(); 
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
        Editar_ApellidoMaterno();
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
        Editar_Contrasena();
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        // TODO add your handling code here:
        if (modo==0){
         Cargar_Datos_Personales(); 
        }
        else{
         Cargar_Datos_Empleado();
        }
    }//GEN-LAST:event_btnResetearActionPerformed

    private void menuResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuResetearActionPerformed
        // TODO add your handling code here:
        if (modo==0){
         Cargar_Datos_Personales(); 
        }
        else{
         Cargar_Datos_Empleado();
        }
    }//GEN-LAST:event_menuResetearActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        // TODO add your handling code here:
        if (modo==0){
        Guardar_Personal();}
        else{
        Guardar_Empleado();}
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void comboEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpleadosActionPerformed
        // TODO add your handling code here:
        Seleccionar_Empleado();
    }//GEN-LAST:event_comboEmpleadosActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
        Editar_Nombre();
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidoMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoMaternoFocusLost
        // TODO add your handling code here:
        Editar_ApellidoMaterno();
    }//GEN-LAST:event_txtApellidoMaternoFocusLost

    private void txtApellidoPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoPaternoFocusLost
        // TODO add your handling code here:
         Editar_ApellidoPaterno(); 
    }//GEN-LAST:event_txtApellidoPaternoFocusLost

    private void txtContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaFocusLost
        // TODO add your handling code here:
        Editar_Contrasena();
    }//GEN-LAST:event_txtContrasenaFocusLost

    private void txtNumerodeUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumerodeUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerodeUsuarioFocusLost

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
        Editar_Usuario();
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtAntiguedadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAntiguedadFocusLost
        // TODO add your handling code here:
        Editar_Antiguedad();
    }//GEN-LAST:event_txtAntiguedadFocusLost

    private void txtEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadFocusLost
        // TODO add your handling code here:
        Editar_Edad();
    }//GEN-LAST:event_txtEdadFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Edicion_de_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Edicion_de_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Edicion_de_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Edicion_de_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Edicion_de_Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnResetear;
    private javax.swing.JComboBox<String> comboEmpleados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAntiguedad;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNumerodeUsuario;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTipodeEmpleado;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuRegresar;
    private javax.swing.JMenuItem menuResetear;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JFormattedTextField txtAntiguedad;
    private javax.swing.JFormattedTextField txtApellidoMaterno;
    private javax.swing.JFormattedTextField txtApellidoPaterno;
    private javax.swing.JFormattedTextField txtArea;
    private javax.swing.JFormattedTextField txtContrasena;
    private javax.swing.JFormattedTextField txtEdad;
    private javax.swing.JFormattedTextField txtNombre;
    private javax.swing.JFormattedTextField txtNumerodeUsuario;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JFormattedTextField txtTipodeEmpleado;
    private javax.swing.JFormattedTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    public void Modificar_Información_Personal(Clase_Identificador_de_Usuario Identificador_de_Usuario) {
      modo=0;//Modo de Edición Personal.
      this.Identificador_de_Usuario_Editor=new Clase_Identificador_de_Usuario();
      this.Identificador_de_Usuario_Editor=Identificador_de_Usuario;
      Persona_Editor=new Clase_Persona();
      Persona_Editor=Personal.getItem(Identificador_de_Usuario.Numero_de_Area).getItem(Identificador_de_Usuario.Numero_de_Empleado);
      Habilitar_Campos();
      Deshabilitar_Campos();
      comboEmpleados.removeAllItems();
      comboEmpleados.setEnabled(false);
      tablaEmpleados.removeAll();
      tablaEmpleados.setEnabled(false);
      Cargar_Datos();
      inicializado=true;
    }
    private void Cargar_Datos(){
      txtNombre.setText(Persona_Editor.getNombre());
      txtApellidoPaterno.setText(Persona_Editor.getApellido_Paterno());
      txtApellidoMaterno.setText(Persona_Editor.getApellido_Materno());
      txtArea.setText(Persona_Editor.getArea());
      txtUsuario.setText(Persona_Editor.getUsuario());
      txtSalario.setText(""+Persona_Editor.getSalario());
      txtAntiguedad.setText(""+Persona_Editor.Antiguedad);
      txtEdad.setText(""+Persona_Editor.Edad);
      txtNumerodeUsuario.setText(""+Persona_Editor.getNumero_Usuario());
      txtTipodeEmpleado.setText(Persona_Editor.get_Tipo_de_Empleado());
      txtContrasena.setText(Persona_Editor.getContrasena());
    }
    private void Habilitar_Campos() {
     txtNombre.setEditable(true);
     txtApellidoPaterno.setEditable(true);
     txtApellidoMaterno.setEditable(true);
     txtArea.setEditable(true);
     txtUsuario.setEditable(true);
     txtSalario.setEditable(true);
     txtAntiguedad.setEditable(true);
     txtEdad.setEditable(true);
     txtNumerodeUsuario.setEditable(true);
     txtTipodeEmpleado.setEditable(true);
     lblContrasena.setVisible(true);
     txtContrasena.setVisible(true);
     txtContrasena.setEditable(true);  
    }
    private void Deshabilitar_Campos() {
      switch (Persona_Editor.getTipo_de_Empleado()) {
            case 0:
                txtArea.setEditable(false);
                txtNumerodeUsuario.setEditable(false);
                txtTipodeEmpleado.setEditable(false);
                break;
            case 1:
                txtArea.setEditable(false);
                txtSalario.setEditable(false);
                txtNumerodeUsuario.setEditable(false);
                txtTipodeEmpleado.setEditable(false);
                break;
            case 2:
                txtArea.setEditable(false);
                txtSalario.setEditable(false);
                txtAntiguedad.setEditable(false);
                txtNumerodeUsuario.setEditable(false);
                txtTipodeEmpleado.setEditable(false);
                break;
            case 3:
                txtArea.setEditable(false);
                txtSalario.setEditable(false);
                txtAntiguedad.setEditable(false);
                txtNumerodeUsuario.setEditable(false);
                txtTipodeEmpleado.setEditable(false);
                break;
            default:
                txtArea.setEditable(false);
                txtSalario.setEditable(false);
                txtAntiguedad.setEditable(false);
                txtNumerodeUsuario.setEditable(false);
                txtTipodeEmpleado.setEditable(false);
                break;
        }    
    }
    private void Guardar_Personal() {
      Persona_Editor.Nombre=txtNombre.getText();
      Persona_Editor.Apellido_Paterno=txtApellidoPaterno.getText();
      Persona_Editor.Apellido_Materno=txtApellidoMaterno.getText();
      Persona_Editor.Usuario=txtUsuario.getText();
      Persona_Editor.Salario=Float.valueOf(txtSalario.getText());
      Persona_Editor.Antiguedad=Float.valueOf(txtAntiguedad.getText());
      float edad=Float.valueOf(txtEdad.getText());
      Persona_Editor.Edad=(int)edad;
      Persona_Editor.Contrasena=txtContrasena.getText();  
    }
    private void Cargar_Datos_Personales() {
       Cargar_Datos();
    }
    
    
    public void Modificar_Informacion_Empleados(Clase_Identificador_de_Usuario Identificador_de_Usuario){
     modo=1;
     this.Identificador_de_Usuario_Editor=new Clase_Identificador_de_Usuario();
     this.Identificador_de_Usuario_Editor=Identificador_de_Usuario;
     Persona_Editor=new Clase_Persona();
     Persona_Editor=Personal.getItem(Identificador_de_Usuario.Numero_de_Area).getItem(Identificador_de_Usuario.Numero_de_Empleado);
     Habilitar_Campos_Empleados();
     Deshabilitar_Campos_Empleados();
     comboEmpleados.removeAllItems();
     Identificadores_de_Usuarios.removeAllItems();
     comboEmpleados.setEnabled(true);
     tablaEmpleados.removeAll();
     tablaEmpleados.setEnabled(true);
     Cargar_Empleados();
     Cargar_Datos_Empleado();
     inicializado=true;
    }
    private void Habilitar_Campos_Empleados() {
     txtNombre.setEditable(true);
     txtApellidoPaterno.setEditable(true);
     txtApellidoMaterno.setEditable(true);
     txtArea.setEditable(true);
     txtUsuario.setEditable(true);
     txtSalario.setEditable(true);
     txtAntiguedad.setEditable(true);
     txtEdad.setEditable(true);
     txtNumerodeUsuario.setEditable(true);
     txtTipodeEmpleado.setEditable(true);
     lblContrasena.setVisible(false);
     txtContrasena.setVisible(false);
     txtContrasena.setEditable(false);   
    }
    private void Deshabilitar_Campos_Empleados() {
     switch (Persona_Editor.getTipo_de_Empleado()) {
            case 0:
                txtArea.setEditable(false);
                txtNumerodeUsuario.setEditable(false);
                txtTipodeEmpleado.setEditable(false);
                break;
            case 1:
                txtArea.setEditable(false);
                txtNumerodeUsuario.setEditable(false);
                txtTipodeEmpleado.setEditable(false);
                break;
            default:
                txtArea.setEditable(false);
                txtSalario.setEditable(true);
                txtNumerodeUsuario.setEditable(false);
                txtTipodeEmpleado.setEditable(false);
                break;
        }       
    }
    private void Cargar_Empleados() {
     Identificadores_de_Usuarios=new Clase_Identificadores_de_Usuarios();
     switch (Persona_Editor.getTipo_de_Empleado()) {
            case 0:
                Cargar_Empleados_Gerente();
                break;
            case 1:
                Cargar_Empleados_Recursos_Humanos();
                break;
            default:
                Cargar_Empleados_Jefe();
                break;
        }
     int i;
     for (i=0;i<Identificadores_de_Usuarios.getSize();i++){
       Actualizar_Persona_Seleccionada(i);
       Agregar_Columna();
     }
      Persona_Seleccionada=new Clase_Persona();
      Identificador_de_Usuario_Seleccionado=new Clase_Identificador_de_Usuario();
      Identificador_de_Usuario_Seleccionado=Identificadores_de_Usuarios.getItem(0);
      Persona_Seleccionada=Personal.getItem(Identificador_de_Usuario_Seleccionado.Numero_de_Area).getItem(Identificador_de_Usuario_Seleccionado.Numero_de_Empleado);
    }
    private void Cargar_Empleados_Gerente() {
      int j,i,Numero_de_Areas=Personal.getSize();
      for (j=1;j<Numero_de_Areas;j++){
       int Numero_de_Empleados=Personal.getItem(j).getSize();
       for (i=0;i<Numero_de_Empleados;i++){
         Persona_Seleccionada=new Clase_Persona();
         Identificador_de_Usuario_Seleccionado=new Clase_Identificador_de_Usuario(j,i);
         Persona_Seleccionada=Personal.getItem(j).getItem(i);
         comboEmpleados.addItem(Persona_Seleccionada.getNombre()+" "+Persona_Seleccionada.getApellido_Paterno()+" "+Persona_Seleccionada.getApellido_Materno()+" ("+Persona_Seleccionada.getUsuario()+")");
         //comboEmpleados.addItem("("+Persona_Seleccionada.getUsuario()+")");
         Identificadores_de_Usuarios.addItem(Identificador_de_Usuario_Seleccionado);
       }
      }
    }
    private void Cargar_Empleados_Recursos_Humanos() {
        int j,i,Numero_de_Areas=Personal.getSize();
      for (j=2;j<Numero_de_Areas;j++){
       int Numero_de_Empleados=Personal.getItem(j).getSize();
       for (i=0;i<Numero_de_Empleados;i++){
         Persona_Seleccionada=new Clase_Persona();
         Identificador_de_Usuario_Seleccionado=new Clase_Identificador_de_Usuario(j,i);
         Persona_Seleccionada=Personal.getItem(j).getItem(i);
         comboEmpleados.addItem(Persona_Seleccionada.getNombre()+" "+Persona_Seleccionada.getApellido_Paterno()+" "+Persona_Seleccionada.getApellido_Materno()+" ("+Persona_Seleccionada.getUsuario()+")");
         //comboEmpleados.addItem("("+Persona_Seleccionada.getUsuario()+")");
         Identificadores_de_Usuarios.addItem(Identificador_de_Usuario_Seleccionado);
       }
      }
    }
    private void Cargar_Empleados_Jefe() {
      int i;
      int j=Identificador_de_Usuario_Editor.Numero_de_Area;
       int Numero_de_Empleados=Personal.getItem(j).getSize();
       for (i=0;i<Numero_de_Empleados;i++){
         Persona_Seleccionada=new Clase_Persona();
         Persona_Seleccionada=Personal.getItem(j).getItem(i);
         if(Persona_Seleccionada.getTipo_de_Empleado()!=2){
         comboEmpleados.addItem(Persona_Seleccionada.getNombre()+" "+Persona_Seleccionada.getApellido_Paterno()+" "+Persona_Seleccionada.getApellido_Materno()+" ("+Persona_Seleccionada.getUsuario()+")");
         Identificador_de_Usuario_Seleccionado=new Clase_Identificador_de_Usuario(j,i);
         Identificadores_de_Usuarios.addItem(Identificador_de_Usuario_Seleccionado);}
       }
    }
    private void Guardar_Empleado() {
      inicializado=false;
      Persona_Seleccionada.Nombre=txtNombre.getText();
      Persona_Seleccionada.Apellido_Paterno=txtApellidoPaterno.getText();
      Persona_Seleccionada.Apellido_Materno=txtApellidoMaterno.getText();
      Persona_Seleccionada.Usuario=txtUsuario.getText();
      Persona_Seleccionada.Salario=Float.valueOf(txtSalario.getText());
      Persona_Seleccionada.Antiguedad=Float.valueOf(txtAntiguedad.getText());
      float edad=Float.valueOf(txtEdad.getText());
      Persona_Seleccionada.Edad=(int)edad;
      //Object Objeto=new Object({});
      
      int i,a=comboEmpleados.getSelectedIndex();
      int b=Identificadores_de_Usuarios.getSize();
      comboEmpleados.removeAllItems();
      while(Tabla.getRowCount()>0){
         Tabla.removeRow(0);
      }
      for (i=0;i<b;i++){
       Persona_Seleccionada =new Clase_Persona();
       Persona_Seleccionada=Personal.getItem(Identificadores_de_Usuarios.getItem(i).Numero_de_Area).getItem(Identificadores_de_Usuarios.getItem(i).Numero_de_Empleado);
       comboEmpleados.addItem(Persona_Seleccionada.getNombre()+" "+Persona_Seleccionada.getApellido_Paterno()+" "+Persona_Seleccionada.getApellido_Materno()+" ("+Persona_Seleccionada.getUsuario()+")");
       Agregar_Columna();
      }
      Persona_Seleccionada =new Clase_Persona();
      Identificador_de_Usuario_Seleccionado=new Clase_Identificador_de_Usuario();
      Identificador_de_Usuario_Seleccionado=Identificadores_de_Usuarios.getItem(a);
      Persona_Seleccionada=Personal.getItem(Identificadores_de_Usuarios.getItem(a).Numero_de_Area).getItem(Identificadores_de_Usuarios.getItem(a).Numero_de_Empleado);
      comboEmpleados.setSelectedIndex(a);
      inicializado=true;
    }
    private void Cargar_Datos_Empleado() {
      txtNombre.setText(Persona_Seleccionada.getNombre());
      txtApellidoPaterno.setText(Persona_Seleccionada.getApellido_Paterno());
      txtApellidoMaterno.setText(Persona_Seleccionada.getApellido_Materno());
      txtArea.setText(Persona_Seleccionada.getArea());
      txtUsuario.setText(Persona_Seleccionada.getUsuario());
      txtSalario.setText(""+Persona_Seleccionada.getSalario());
      txtAntiguedad.setText(""+Persona_Seleccionada.Antiguedad);
      txtEdad.setText(""+Persona_Seleccionada.Edad);
      txtNumerodeUsuario.setText(""+Persona_Seleccionada.getNumero_Usuario());
      txtTipodeEmpleado.setText(Persona_Seleccionada.get_Tipo_de_Empleado());
      txtContrasena.setText(Persona_Seleccionada.getContrasena());   
    }
    private void Seleccionar_Empleado() {
      if (inicializado){
      int a=comboEmpleados.getSelectedIndex();
      Persona_Seleccionada=new Clase_Persona();
      Identificador_de_Usuario_Seleccionado=new Clase_Identificador_de_Usuario();
      Identificador_de_Usuario_Seleccionado=Identificadores_de_Usuarios.getItem(a);
      Persona_Seleccionada=Personal.getItem(Identificador_de_Usuario_Seleccionado.Numero_de_Area).getItem(Identificador_de_Usuario_Seleccionado.Numero_de_Empleado);
      Cargar_Datos_Empleado();
      }
    }
    private void Agregar_Columna() {
     String Datos[]=new String[7];
     Datos[0]=Persona_Seleccionada.getNombre()+" "+Persona_Seleccionada.getApellido_Paterno()+" "+Persona_Seleccionada.getApellido_Materno();
     Datos[1]=Persona_Seleccionada.getArea();
     Datos[2]=Persona_Seleccionada.get_Tipo_de_Empleado();
     Datos[3]=Persona_Seleccionada.getUsuario();
     Datos[4]=""+Persona_Seleccionada.getNumero_Usuario();
     Datos[5]=""+Persona_Seleccionada.getEdad();
     Datos[6]=""+Persona_Seleccionada.getSalario();
     Tabla.addRow(Datos);
    }
    private void Actualizar_Persona_Seleccionada(int i){
    Persona_Seleccionada =new Clase_Persona();
    Identificador_de_Usuario_Seleccionado= new Clase_Identificador_de_Usuario();
    Identificador_de_Usuario_Seleccionado=Identificadores_de_Usuarios.getItem(i);
    Persona_Seleccionada=Personal.getItem(Identificador_de_Usuario_Seleccionado.Numero_de_Area).getItem(Identificador_de_Usuario_Seleccionado.Numero_de_Empleado);
  }

    private void Editar_Nombre(){
        if(!Personal.Quedar_con_Texto(txtNombre.getText())){
         JOptionPane.showMessageDialog(null, "Ingrese un Nombre válido (con carácteres).",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE); 
         if (modo==0){
          txtNombre.setText(Persona_Editor.getNombre());}
         else{
          txtNombre.setText(Persona_Seleccionada.getNombre());}
        }
    }
    private void Editar_ApellidoPaterno(){
        if(!Personal.Quedar_con_Texto(txtApellidoPaterno.getText())){
          JOptionPane.showMessageDialog(null, "Ingrese un Apellido Paterno válido (con carácteres).",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE); 
          if (modo==0){
          txtApellidoPaterno.setText(Persona_Editor.getApellido_Paterno());}
        else{
          txtApellidoPaterno.setText(Persona_Seleccionada.getApellido_Paterno());}
        }
    }
    private void Editar_ApellidoMaterno(){
        if(!Personal.Quedar_con_Texto(txtApellidoMaterno.getText())){
         JOptionPane.showMessageDialog(null, "Ingrese un Apellido Paterno válido (con carácteres).",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);  
         if (modo==0){
          txtApellidoMaterno.setText(Persona_Editor.getApellido_Materno());}
         else{
          txtApellidoMaterno.setText(Persona_Seleccionada.getApellido_Materno());}
        }
    }

    private void Editar_Contrasena() {
       if(!Personal.Contrasena_valida((txtContrasena.getText()))){
         JOptionPane.showMessageDialog(null, "Ingrese una contraseña válida (con mas de 5 carácteres).",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);  
         if (modo==0){
          txtContrasena.setText(Persona_Editor.getContrasena());}
         else{
          txtContrasena.setText(Persona_Seleccionada.getContrasena());}
        } 
    }

    private void Editar_Usuario() {
         if (modo==0){
          if(!Personal.Mismo_Usuario(Persona_Editor.getUsuario(),txtUsuario.getText())&&(Personal.Usuario_Repetido(txtUsuario.getText())||!Personal.Quedar_con_Texto(txtUsuario.getText()))){
            txtUsuario.setText(Persona_Editor.getUsuario());
            Mostrar_Mensaje_Usuario();  
          }
         }
         else{
          if(!Personal.Mismo_Usuario(Persona_Seleccionada.getUsuario(),txtUsuario.getText())&&(Personal.Usuario_Repetido(txtUsuario.getText())||!Personal.Quedar_con_Texto(txtUsuario.getText()))){   
           txtUsuario.setText(Persona_Seleccionada.getUsuario());
           Mostrar_Mensaje_Usuario();
          }
         }     
    }
    private void Mostrar_Mensaje_Usuario(){
      JOptionPane.showMessageDialog(null, "Ingrese un usuario no repetido y con mas de 3 carácteres",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
    }

    private void Editar_Salario() {
        String Salario=txtSalario.getText();
        try{
          //double Sal=Double.valueOf(Salario);
          if(!Personal.Determinar_Salario_Valido(Salario)){
            if(modo==0){
             txtSalario.setText(""+Persona_Editor.getSalario());
             JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 200*10^6",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            else{
             txtSalario.setText(""+Persona_Seleccionada.getSalario());
             JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 200*10^6",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
          }
           
        }
        catch(NumberFormatException e){
          if(modo==0){
             txtSalario.setText(""+Persona_Editor.getSalario());
            }
          else{
             txtSalario.setText(""+Persona_Seleccionada.getSalario());
          }
          JOptionPane.showMessageDialog(null, "Ingrese un número (no alfanumérico)",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void Editar_Antiguedad() {
        String Antiguedad=txtAntiguedad.getText();
        String Edad=txtEdad.getText();
        try{
          //double Sal=Double.valueOf(Salario);
          if(!Personal.Determinar_Antiguedad_Valida(Antiguedad,Edad)){
            if(modo==0){
             txtAntiguedad.setText(""+Persona_Editor.getAntiguedad());
             JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 150 y menor a la Edad",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            else{
             txtAntiguedad.setText(""+Persona_Seleccionada.getAntiguedad());
             JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 150 y menor a la Edad",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
          }
        }
        catch(NumberFormatException e){
          if(modo==0){
             txtAntiguedad.setText(""+Persona_Editor.getAntiguedad());
            }
          else{
             txtAntiguedad.setText(""+Persona_Seleccionada.getAntiguedad());
          }
          JOptionPane.showMessageDialog(null, "Ingrese un número (no alfanumérico)",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void Editar_Edad() {
        String Antiguedad=txtAntiguedad.getText();
        String Edad=txtEdad.getText();
        try{
          //double Sal=Double.valueOf(Salario);
          if(!Personal.Determinar_Edad_Valida(Antiguedad,Edad)){
            if(modo==0){
             txtEdad.setText(""+Persona_Editor.getEdad());
             JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 150 y mayor a la Antiguedad",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            else{
             txtEdad.setText(""+Persona_Seleccionada.getEdad());
             JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 150 y mayor a la Antiguedad",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
          }
        }
        catch(NumberFormatException e){
          if(modo==0){
             txtEdad.setText(""+Persona_Editor.getEdad());
            }
          else{
             txtEdad.setText(""+Persona_Seleccionada.getEdad());
          }
          JOptionPane.showMessageDialog(null, "Ingrese un número (no alfanumérico)",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
}