/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_app;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyecto_app.Proyecto_APP.*;

/**
 *
 * @author LuisFernando
 */
public class Ventana_Agregar_Empleados extends javax.swing.JFrame {
    Clase_Persona Persona_Editor,Persona_Seleccionada;
    Clase_Identificador_de_Usuario Identificador_de_Usuario_Editor,Identificador_de_Usuario_Seleccionado;
    Clase_Identificadores_de_Usuarios Identificadores_de_Usuarios;
    boolean inicializado=false;
    DefaultTableModel Tabla=new DefaultTableModel();
    Clase_Gerente Gerente;
    Clase_Recursos_Humanos Recurso_Humano;
    Clase_Jefe Jefe;
    Clase_Ingeniero Ingeniero;
    Clase_Obrero Obrero;
    int Opciones=0;
    Clase_Usuario Usuario;
    /**
     * Creates new form Ventana_Agregar_Empleados
     */
    public Ventana_Agregar_Empleados() {
        initComponents();
        Gerente=new Clase_Gerente();
        Recurso_Humano=new Clase_Recursos_Humanos();
        Jefe=new Clase_Jefe();
        Ingeniero=new Clase_Ingeniero();
        Obrero=new Clase_Obrero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblArea = new javax.swing.JLabel();
        comboArea = new javax.swing.JComboBox<>();
        lblTipodeEmpleado = new javax.swing.JLabel();
        comboEmpleado = new javax.swing.JComboBox<>();
        lblNombre1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        txtNombre = new javax.swing.JFormattedTextField();
        txtApellidoPaterno = new javax.swing.JFormattedTextField();
        txtApellidoMaterno = new javax.swing.JFormattedTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JFormattedTextField();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JFormattedTextField();
        lblAntiguedad = new javax.swing.JLabel();
        txtAntiguedad = new javax.swing.JFormattedTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JFormattedTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JFormattedTextField();
        btnGuardar = new javax.swing.JButton();
        btnResetear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuRegresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        lblArea.setText("Área:");

        comboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaActionPerformed(evt);
            }
        });

        lblTipodeEmpleado.setText("Tipo de Empleado:");

        comboEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNombre1.setText("Datos");

        lblNombre.setText("Nombre:");

        lblApellidoPaterno.setText("Apellido Paterno:");

        lblApellidoMaterno.setText("Apellido Materno:");

        txtNombre.setText("txtNombre");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellidoPaterno.setText("txtApellidoPaterno");
        txtApellidoPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoPaternoFocusLost(evt);
            }
        });
        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });

        txtApellidoMaterno.setText("txtApellidoMaterno");
        txtApellidoMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoMaternoFocusLost(evt);
            }
        });
        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });

        lblUsuario.setText("Usuario:");

        txtUsuario.setText("txtUsuario");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblSalario.setText("Salario:");

        txtSalario.setText("txtSalario");
        txtSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalarioFocusLost(evt);
            }
        });
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        lblAntiguedad.setText("Antiguedad:");

        txtAntiguedad.setText("txtAntiguedad");
        txtAntiguedad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAntiguedadFocusLost(evt);
            }
        });
        txtAntiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAntiguedadActionPerformed(evt);
            }
        });

        lblEdad.setText("Edad:");

        txtEdad.setText("txtEdad");
        txtEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadFocusLost(evt);
            }
        });
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        lblContrasena.setText("Contraseña:");

        txtContrasena.setText("txtContrasena");
        txtContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrasenaFocusLost(evt);
            }
        });
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnResetear.setText("Resetear");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblApellidoPaterno)
                            .addComponent(lblApellidoMaterno))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblContrasena)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblTipodeEmpleado)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblArea)
                                    .addGap(77, 77, 77)
                                    .addComponent(comboArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAntiguedad)
                                        .addComponent(lblSalario)
                                        .addComponent(lblUsuario))
                                    .addGap(45, 45, 45)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblEdad)
                                .addGap(76, 76, 76)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnGuardar)
                        .addGap(81, 81, 81)
                        .addComponent(btnResetear))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblNombre1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblNombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoPaterno)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoMaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(comboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAntiguedad)
                    .addComponent(txtAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipodeEmpleado)
                    .addComponent(comboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnResetear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Acciones");

        menuRegresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuRegresar.setText("Regresar");
        menuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegresarActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegresar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegresarActionPerformed
        // TODO add your handling code here:
        inicializado=false;
        Personal.Numero_de_Usuario=Personal.Numero_de_Usuario-1;
        Principal.Cargar_datos_de_Usuario(Identificador_de_Usuario_Editor);
        Principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuRegresarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        Editar_Nombre();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
        Editar_ApellidoPaterno();
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
         Editar_ApellidoMaterno();
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        Editar_Usuario();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
        Editar_Salario();
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAntiguedadActionPerformed
        // TODO add your handling code here:
        Editar_Antiguedad();
    }//GEN-LAST:event_txtAntiguedadActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
        Editar_Edad();
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
        Editar_Contrasena();
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void comboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaActionPerformed
        // TODO add your handling code here:
        if (inicializado){
         Cargar_Tipo_de_Empleados();
        }
    }//GEN-LAST:event_comboAreaActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        // TODO add your handling code here:
     txtNombre.setText(Persona_Seleccionada.getNombre());
     txtApellidoPaterno.setText(Persona_Seleccionada.getApellido_Paterno());
     txtApellidoMaterno.setText(Persona_Seleccionada.getApellido_Materno());
     txtUsuario.setText(Persona_Seleccionada.getUsuario());
     txtSalario.setText(""+Persona_Seleccionada.getSalario());
     txtAntiguedad.setText(""+Persona_Seleccionada.Antiguedad);
     txtEdad.setText(""+Persona_Seleccionada.Edad);
     txtContrasena.setText(Persona_Seleccionada.getContrasena());
    }//GEN-LAST:event_btnResetearActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Agregar_Empleado();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
        Editar_Nombre();
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidoPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoPaternoFocusLost
        // TODO add your handling code here:
         Editar_ApellidoPaterno();
    }//GEN-LAST:event_txtApellidoPaternoFocusLost

    private void txtApellidoMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoMaternoFocusLost
        // TODO add your handling code here:
        Editar_ApellidoMaterno();
    }//GEN-LAST:event_txtApellidoMaternoFocusLost

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
        Editar_Usuario();
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalarioFocusLost
        // TODO add your handling code here:
        Editar_Salario();
    }//GEN-LAST:event_txtSalarioFocusLost

    private void txtAntiguedadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAntiguedadFocusLost
        // TODO add your handling code here:
        Editar_Antiguedad();
    }//GEN-LAST:event_txtAntiguedadFocusLost

    private void txtEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadFocusLost
        // TODO add your handling code here:
        Editar_Edad();
    }//GEN-LAST:event_txtEdadFocusLost

    private void txtContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrasenaFocusLost
        // TODO add your handling code here:
        Editar_Contrasena();
    }//GEN-LAST:event_txtContrasenaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Agregar_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Agregar_Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnResetear;
    private javax.swing.JComboBox<String> comboArea;
    private javax.swing.JComboBox<String> comboEmpleado;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAntiguedad;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTipodeEmpleado;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuRegresar;
    private javax.swing.JFormattedTextField txtAntiguedad;
    private javax.swing.JFormattedTextField txtApellidoMaterno;
    private javax.swing.JFormattedTextField txtApellidoPaterno;
    private javax.swing.JFormattedTextField txtContrasena;
    private javax.swing.JFormattedTextField txtEdad;
    private javax.swing.JFormattedTextField txtNombre;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JFormattedTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void Agregar_Datos_de_Empleado(Clase_Identificador_de_Usuario Identificador_de_Usuario) {
     this.Identificador_de_Usuario_Editor=new Clase_Identificador_de_Usuario();
     this.Identificador_de_Usuario_Editor=Identificador_de_Usuario;
     Persona_Editor=new Clase_Persona();
     Persona_Editor=Personal.getItem(Identificador_de_Usuario.Numero_de_Area).getItem(Identificador_de_Usuario.Numero_de_Empleado);
     comboArea.removeAllItems();
     comboEmpleado.removeAllItems();
     Cargar_Menu();
     Cargar_Datos_de_Nuevo_Empleado();
     inicializado=true;    
    }

    private void Cargar_Menu() {
        int i;
        if(Persona_Editor.getTipo_de_Empleado()==0){
            Seleccionar_Gerente();
            for (i=0;i<Personal.getSize();i++){
            comboArea.addItem(Personal.getItem(i).getNombre_del_Area());}
        }
        else{
           Seleccionar_Recursos_Humanos();
           for (i=1;i<Personal.getSize();i++){
           comboArea.addItem(Personal.getItem(i).getNombre_del_Area());}
        }
    }

    private void Cargar_Datos_de_Nuevo_Empleado() {
     /*switch (Opciones) {
                case 0:
                     Persona_Seleccionada=new Clase_Gerente();
                    break;
                case 1:
                     Persona_Seleccionada=new Clase_Recursos_Humanos();
                    break;
                default:
                    switch (comboEmpleado.getSelectedIndex()) {
                     case 0:
                      Persona_Seleccionada=new Clase_Jefe();
                      break;
                     case 1:
                      Persona_Seleccionada=new Clase_Ingeniero();
                      break;
                     default:
                      Persona_Seleccionada=new Clase_Obrero();
                      break;
                    }
                    break;
            }*/
     Persona_Seleccionada=new Clase_Persona();
     Usuario=Personal.Regresar_Numero_de_Usuario();
     Persona_Seleccionada.setUsuario(Usuario);
     txtNombre.setText(Persona_Seleccionada.getNombre());
     txtApellidoPaterno.setText(Persona_Seleccionada.getApellido_Paterno());
     txtApellidoMaterno.setText(Persona_Seleccionada.getApellido_Materno());
     txtUsuario.setText(Persona_Seleccionada.getUsuario());
     txtSalario.setText(""+Persona_Seleccionada.getSalario());
     txtAntiguedad.setText(""+Persona_Seleccionada.Antiguedad);
     txtEdad.setText(""+Persona_Seleccionada.Edad);
     txtContrasena.setText(Persona_Seleccionada.getContrasena());
    }   

    private void Cargar_Tipo_de_Empleados() {
        int a;
        comboEmpleado.removeAllItems();
        a=comboArea.getSelectedIndex();
        if(Persona_Editor.getTipo_de_Empleado()==0){
            switch (a) {
                case 0:
                    Seleccionar_Gerente();
                    break;
                case 1:
                    Seleccionar_Recursos_Humanos();
                    break;
                default:
                    Seleccionar_Empleados();
                    break;
            }
        }
        else{
          switch (a) {
                case 0:
                    Seleccionar_Recursos_Humanos();
                    break;
                default:
                    Seleccionar_Empleados();
                    break;
            }  
        }
    }
    private void Seleccionar_Gerente() {
      comboEmpleado.addItem(Gerente.get_Tipo_de_Empleado());
      Opciones=0;
    }
    
    private void Seleccionar_Recursos_Humanos() {
      comboEmpleado.addItem(Recurso_Humano.get_Tipo_de_Empleado());
      Opciones=1;
    }
    private void Seleccionar_Empleados() {
      comboEmpleado.addItem(Jefe.get_Tipo_de_Empleado());
      comboEmpleado.addItem(Ingeniero.get_Tipo_de_Empleado());
      comboEmpleado.addItem(Obrero.get_Tipo_de_Empleado());
      Opciones=2;
    }

    private void Agregar_Empleado() {
      switch (Opciones) {
                case 0:
                     Persona_Seleccionada=new Clase_Gerente();
                    break;
                case 1:
                     Persona_Seleccionada=new Clase_Recursos_Humanos();
                    break;
                default:
                    switch (comboEmpleado.getSelectedIndex()) {
                     case 0:
                      Persona_Seleccionada=new Clase_Jefe();
                      break;
                     case 1:
                      Persona_Seleccionada=new Clase_Ingeniero();
                      break;
                     default:
                      Persona_Seleccionada=new Clase_Obrero();
                      break;
                    }
                    break;
            }
     int area=comboArea.getSelectedIndex();
     if(Persona_Editor.getTipo_de_Empleado()==1){
      area=area+1;
     }
     Persona_Seleccionada.setArea(Personal.getItem(area).getNombre_del_Area());
     Persona_Seleccionada.setNombre(txtNombre.getText());
     Persona_Seleccionada.setApellido_Paterno(txtApellidoPaterno.getText());
     Persona_Seleccionada.setApellido_Materno(txtApellidoMaterno.getText());
     Persona_Seleccionada.setUsuario(txtUsuario.getText());
     Persona_Seleccionada.setSalario(Float.valueOf(txtSalario.getText()));
     Persona_Seleccionada.setAntiguedad(Float.valueOf(txtAntiguedad.getText()));
      float edad=Float.valueOf(txtEdad.getText());
     Persona_Seleccionada.setEdad((int)edad);
     Persona_Seleccionada.setContrasena(txtContrasena.getText());
     Persona_Seleccionada.setNumero_Usuario(Usuario.getUsuario());
     Persona_Seleccionada.setNumero_Area(area);
     Personal.getItem(area).Agregar_Empleado(Persona_Seleccionada);
     inicializado=false;
     Principal.Cargar_datos_de_Usuario(Identificador_de_Usuario_Editor);
     Principal.setVisible(true);
     this.setVisible(false);
    }
    private void Editar_Nombre(){
        if(!Personal.Quedar_con_Texto(txtNombre.getText())){
         JOptionPane.showMessageDialog(null, "Ingrese un Nombre válido (con carácteres).",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE); 
          txtNombre.setText(Persona_Seleccionada.getNombre());}
    }
    private void Editar_ApellidoPaterno(){
        if(!Personal.Quedar_con_Texto(txtApellidoPaterno.getText())){
          JOptionPane.showMessageDialog(null, "Ingrese un Apellido Paterno válido (con carácteres).",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
          txtApellidoPaterno.setText(Persona_Seleccionada.getApellido_Paterno());}
    }
    private void Editar_ApellidoMaterno(){
        if(!Personal.Quedar_con_Texto(txtApellidoMaterno.getText())){
         JOptionPane.showMessageDialog(null, "Ingrese un Apellido Paterno válido (con carácteres).",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
          txtApellidoMaterno.setText(Persona_Seleccionada.getApellido_Materno());}
    }

    private void Editar_Contrasena(){
       if(!Personal.Contrasena_valida((txtContrasena.getText()))){
         JOptionPane.showMessageDialog(null, "Ingrese una contraseña válida (con mas de 5 carácteres).",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);  
          txtContrasena.setText(Persona_Seleccionada.getContrasena());}  
    }

    private void Editar_Usuario(){
          if(!Personal.Mismo_Usuario(Persona_Seleccionada.getUsuario(),txtUsuario.getText())&&(Personal.Usuario_Repetido(txtUsuario.getText())||!Personal.Quedar_con_Texto(txtUsuario.getText()))){   
           txtUsuario.setText(Persona_Seleccionada.getUsuario());
           Mostrar_Mensaje_Usuario();
          }         
    }
    private void Mostrar_Mensaje_Usuario(){
      JOptionPane.showMessageDialog(null, "Ingrese un usuario no repetido y con mas de 3 carácteres",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
    }

    private void Editar_Salario() {
        String Salario=txtSalario.getText();
        try{
          //double Sal=Double.valueOf(Salario);
          if(!Personal.Determinar_Salario_Valido(Salario)){
           txtSalario.setText(""+Persona_Seleccionada.getSalario());
           JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 200*10^6",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
          }
        }
        catch(NumberFormatException e){
          txtSalario.setText(""+Persona_Seleccionada.getSalario());
          JOptionPane.showMessageDialog(null, "Ingrese un número (no alfanumérico)",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void Editar_Antiguedad() {
        String Antiguedad=txtAntiguedad.getText();
        String Edad=txtEdad.getText();
        try{
          //double Sal=Double.valueOf(Salario);
          if(!Personal.Determinar_Antiguedad_Valida(Antiguedad,Edad)){
             txtAntiguedad.setText(""+Persona_Seleccionada.getAntiguedad());
             JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 150 y menor a la Edad",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
          }
        }
        catch(NumberFormatException e){
          txtAntiguedad.setText(""+Persona_Seleccionada.getAntiguedad());
          JOptionPane.showMessageDialog(null, "Ingrese un número (no alfanumérico)",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void Editar_Edad() {
        String Antiguedad=txtAntiguedad.getText();
        String Edad=txtEdad.getText();
        try{
          //double Sal=Double.valueOf(Salario);
          if(!Personal.Determinar_Edad_Valida(Antiguedad,Edad)){
             txtEdad.setText(""+Persona_Seleccionada.getEdad());
             JOptionPane.showMessageDialog(null, "Ingrese un número entre 0 y 150 y mayor a la Antiguedad",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
          }
        }
        catch(NumberFormatException e){
          txtEdad.setText(""+Persona_Seleccionada.getEdad());
          JOptionPane.showMessageDialog(null, "Ingrese un número (no alfanumérico)",
                "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
}
